# Generated by Django 4.0.3 on 2022-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_name', models.CharField(max_length=100)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
