# Generated by Django 4.1 on 2022-08-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptowatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='crypto_name',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Etherium'), ('SOL', 'SOLANA')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cryptowatchlist.crypto')),
            ],
        ),
    ]
