# Generated by Django 4.1 on 2022-08-13 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptowatchlist', '0002_alter_crypto_crypto_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coin',
        ),
        migrations.AddField(
            model_name='crypto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cryptowatchlist.user'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='crypto_name',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Etherium'), ('SOL', 'Solana')], max_length=100, null=True),
        ),
    ]
